### ISSUE TITLE
Research possible code refactorings

### ISSUE THREAD

**Issue by arreche** [AgileVentures/asyncvoter-slack-command#15]
Research different possible refactorings

- [ ] make a list of possible refactorings
- [x] look at other nodejs projects for best practices

Convert this **spike** in something **usable by others**

**Comment by tansaku** [comment]
@arreche concerned that all code is in `async-voter.js`

**Comment by arreche** [comment]
Here are some pointers
- https://www.sitepoint.com/node-js-best-practices-from-the-node-gurus/
- https://www.codementor.io/mattgoldspink/nodejs-best-practices-du1086jja
- https://blog.risingstack.com/node-js-best-practices-2017/
- https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/
- https://github.com/sindresorhus/awesome-nodejs

**Comment by arreche** [comment]
OK. Those are my pics for the first round:

- [ ] Adopt [Express](https://expressjs.com/en/starter/generator.html) conventions
- [ ] Adopt [JavaScript Standard Style](http://standardjs.com/) style guide
- [ ] Switch to [Yarn](https://yarnpkg.com)
- [ ] Split `async-voter.js` code in modules
- [ ] Enable a CI service
- [ ] Enable an uptime monitor service

**Comment by Zsuark** [comment]
Hi @arreche,

My thoughts on this - forgive me if I play devil's advocate at times.

 - [ ] Which Express conventions per se? The code handling express has a nice level of separation of concerns. It is quick to understand and learn. The code also matches the examples given by the Express team.
 - [ ] Previously, we did have an agreed style convention - however, I love that https://standardjs.com/ automates the process in testing.
 - [ ] For this project, what benefits do you see Yarn offering?
 - [ ] `async-voter.js` is 168 lines long, including comments and whitespace. If we divide it up further, it will be more confusing than clear and helpful, no?
 - [ ] CI service would be great. There are heaps of good options. [Travis CI](https://travis-ci.org/) and [CircleCI](https://circleci.com/) are good options.
 - [ ] Would an uptime monitor service be overkill? I know there are free ones available - e.g. [10 Free Services to Monitor...](http://mashable.com/2010/04/09/free-uptime-monitoring/#hSLOK00m7kqP). How much of a need is it and how much maintenance/annoyance would the monitor be?

**Comment by Zsuark** [comment]
Further re express - are you looking at something like: https://expressjs.com/en/advanced/best-practice-performance.html ?
