### ISSUE TITLE
just tried from slack and no response from system

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/asyncvoter-slack-command#16]
```/voter https://waffle.io/AgileVentures/asyncvoter-api/cards/58bcaa00bbf77215009547bd```

tried three times - no joy

**Comment by arreche** [comment]
There was an issue with the SSL certificates but it is working now.

**Comment by tansaku** [comment]
@arreche any notes on how it was fixed?

**Comment by arreche** [comment]
I created a custom domain (https://asyncvoter.tk/) for this application but forgot to issue a new SSL certificate wich is required to communicate with Slack APIs

Here you can see how to issue SSL certificates with dokku-letsencrypt:
- https://github.com/AgileVentures/asyncvoter-slack-command/wiki#3-generating-ssl-certificates-with-dokku-letsencrypt
