### ISSUE TITLE
set up CI for this repo

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/asyncvoter-slack-command#32]
e.g. travis, semaphore etc.

**Comment by Zsuark** [comment]
Travis is already proven to work. Implementing .travis.yml

**Comment by Zsuark** [comment]
.travis.yml already implemented

**Comment by Zsuark** [comment]
I think the hooks may need to be turned on by an administrator - https://travis-ci.org/AgileVentures/asyncvoter-slack-bot

**Comment by tansaku** [comment]
@Zsuark I think I just activated https://travis-ci.org/AgileVentures/asyncvoter-slack-command - I would like to know how we can better share permissions for managing travis ...
