### ISSUE TITLE
persist a user's vote in some way.  for instance, the issue they voted on, what channel, when and their vote size or no-opinion should be saved

### ISSUE THREAD

**Issue by mtc2013** [AgileVentures/asyncvoter-slack-command#33]
This might be integrated in some way with asynchvoter-api or done anew.

**Comment by tansaku** [comment]
As a AV admin
So that we can analyse how people are using the voter
We'd like to persist the voting data 

Options:

1) just put mongodb in instead or redis
2) could hit our separate API system?

**Comment by Zsuark** [comment]
This is now being handled by Mongo in my experimental branches. Keep this idea on hold until we merge it in.
