### ISSUE TITLE
include the title of the issue automatically in the presentation of the vote

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/asyncvoter-slack-command#8]
Actually seems like we can do this with current interface:

![](https://www.dropbox.com/s/n5bvhhi0ggqk171/Screenshot%202017-03-15%2016.31.40.png?dl=1)

**Comment by tansaku** [comment]
could just change text prompt in slack dashboard to suggest to user to include title

**Comment by arreche** [comment]
<img width="810" alt="screen shot 2017-03-15 at 16 49 13" src="https://cloud.githubusercontent.com/assets/459813/23960273/6cd43e76-099f-11e7-9e85-ca04ca8ce9dc.png">

**Comment by tansaku** [comment]
@arreche awesome!
